name: Build Expo App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version you are using
    - name: Install Dependencies
      run: npm install
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Login to Expo
      run: expo login --non-interactive --username ${{ secrets.EXPO_CLI_USERNAME }} --password ${{ secrets.EXPO_CLI_PASSWORD }}
    - name: Build Expo App
      run: expo build:android # or expo build:ios, depending on your target
    - name: Logout of Expo
      run: expo logout
