name: Build Expo App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0" # Specify the Node.js version you are using
      - name: Install Dependencies
        run: npm install
      - name: Login to Expo
        run: npx expo login --non-interactive --username ${{ secrets.EXPO_CLI_USERNAME }} --password ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Build Expo App
        run: npx expo build:ios # or expo build:ios, depending on your target
      - name: Logout of Expo
        run: npx expo logout
